#!/usr/bin/env bash
SELF=$(readlink -f "$0")

function _bash() {
    PATH=$SSHHOME:$PATH exec bash --rcfile <(echo '
    for f in /etc/bash.bashrc "$HOME/.bashrc"; do
      test -f "$f" && source "$f"
    done
    source "$SSHHOME/.sshrc"') "$@"
}

function _sshrc() {
    home=${SSHHOME:-$HOME}
    test -f "$home/.sshrc" || exec echo "No such file: $home/.sshrc" >&2
    sshrcdir=$(test -d "$home/.sshrc.d" && echo '.sshrc.d')
    files=$(tar -czhC "$home" .sshrc $sshrcdir | xxd -p)
    ssh -t "$@" '
        export SSHHOME=$(mktemp -d); export SSHRCCLEANUP=$SSHHOME
        echo "'"$files"'" | xxd -p -r | tar -mxzC "$SSHHOME"
        echo "'"$(xxd -p "$SELF")"'" | xxd -p -r > "$SSHHOME/sshrc"
        chmod +x "$SSHHOME/sshrc"
        ln -s sshrc "$SSHHOME/bashsshrc"
        "$SSHHOME/bashsshrc"
        rm -rf "$SSHRCCLEANUP"'
}

if test "$(basename "$0")" = 'bashsshrc'; then
    _bash "$@"
elif test -n "$1"; then
    _sshrc "$@"
else
    ssh
fi
